version: '3.8'

services:

  uppy:
    container_name: uppy
    # image: chriscarabine/uppy:latest
    build: .	
    networks:
      - upload_network
    ports: 
      - "8080:8080"

networks:
  upload_network:
